# Generated by Django 5.2.4 on 2025-07-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
    ]
